labelDefinitions:
  - name: bug
    color: '00DD00'
    description: 'A bug'
  - name: docs
    color: '4444FF'
    description: 'Documentation update'
  - name: release
    color: 'FF6600123'
    description: 'Targets release branch'
  - name: config
    color: '777700'
  - name: hotfix
    color: 'DD1100'
    description: 'A fix for an issue in production. Needs attention.' 


targetBranchLabels:
  release: 'release-.*'

pathLabels:
  docs: ['*.md']
  config: ['*.yml']
